In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
x=[1,2,4,3,5]
y=[1,3,3,2,5]
mean_x = np.mean(x)
mean_y = np.mean(y)

In [3]:
def linreg(x,y):
 # Using the formula to calculate b1 and b2
 numer = 0
 denom = 0
 m=len(x)
 for i in range(m):
   numer += (x[i] - mean_x) * (y[i] - mean_y)
   denom += (x[i] - mean_x) ** 2


 b1 = numer / denom


 b0 = mean_y - (b1*mean_x)
 print(b1,b0)
 return b1,b0

a=linreg(x,y)
print(a)
b=[]
for i in x:
 b.append((a[0]*i+a[1]))
print(b)

0.8 0.39999999999999947
(0.8, 0.39999999999999947)
[1.1999999999999995, 1.9999999999999996, 3.5999999999999996, 2.8, 4.3999999999999995]


In [4]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/1.01.%20Simple%20linear%20regression.csv")
data.head(2)

SAT   GPA
0  1714  2.40
1  1664  2.52

In [5]:
data.shape

(84, 2)

In [7]:
x=data[["SAT"]].values
x.shape

(84, 1)

In [8]:
z = [data["SAT"]]
#print(x.shape)


x=np.array(z).T
print(x.shape)


y = data["GPA"]
print(y.shape)

(84, 1)
(84,)


In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(x,y)
print('intercept : ',model.intercept_)
print('slope : ',model.coef_)
print(model.predict([[2000]]))


intercept :  0.27504029966028076
slope :  [0.00165569]
[3.5864164]


In [12]:
data=pd.read_csv('C:/Users/abina/OneDrive/Desktop/ML/Tetuan City power consumption.csv')

In [13]:
data.head()

DateTime  Temperature  Humidity  Wind Speed  general diffuse flows  \
0  1/1/2017 0:00        6.559      73.8       0.083                  0.051   
1  1/1/2017 0:10        6.414      74.5       0.083                  0.070   
2  1/1/2017 0:20        6.313      74.5       0.080                  0.062   
3  1/1/2017 0:30        6.121      75.0       0.083                  0.091   
4  1/1/2017 0:40        5.921      75.7       0.081                  0.048   

   diffuse flows  Zone 1 Power Consumption  Zone 2  Power Consumption  \
0          0.119               34055.69620                16128.87538   
1          0.085               29814.68354                19375.07599   
2          0.100               29128.10127                19006.68693   
3          0.096               28228.86076                18361.09422   
4          0.085               27335.69620                17872.34043   

   Zone 3  Power Consumption  
0                20240.96386  
1                20131.08434  
2                19668.43373  
3                18899.27711  
4                18442.40964

In [29]:
x=data[["Temperature","Humidity","Wind Speed"]].values
y=data['Zone 1 Power Consumption'].values

In [30]:
from sklearn.linear_model import LinearRegression

model=LinearRegression().fit(x,y)
model.predict([[30.3,80,0.083]])


array([37871.55939285])

In [31]:
#Assuming your model is stored in a variable called Model
import pickle
with open ('abi.pkl','wb') as file:
    pickle.dump(model,file)

In [32]:
with open('abi.pkl','rb') as file:
    a=pickle.load(file)

In [33]:
a.predict([[30.3,80,0.083]])

array([37871.55939285])

*1.GET DATA*

In [53]:
import matplotlib.pyplot as plt
dataset = pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/student_scores.csv')
dataset.head()
#dataset.shape

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

*2.Select Features and Target*

In [40]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,1].values

*3.Split data*

In [41]:
#split data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

*4.MODEL TRAINING*

In [51]:
#Train MOdel
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(x_train,y_train)
print(model.intercept_)
print(model.coef_)
y_predict=model.predict(x_test)

1.2139649388594265
[10.06790391]


In [43]:
y_predict

array([16.3158208 , 52.56027486, 34.43804783, 33.43125744, 46.51953252,
       75.71645385, 12.28865924, 56.58743642])

In [45]:
df=pd.DataFrame({'Actual':y_test,'Predict':y_predict})
df

Actual    Predict
0      20  16.315821
1      47  52.560275
2      42  34.438048
3      27  33.431257
4      41  46.519533
5      69  75.716454
6      17  12.288659
7      60  56.587436

**5.Evaluation Metrics**

In [46]:
#error calucations
from sklearn import metrics
print('MAE :' , metrics.mean_absolute_error(y_test,y_predict))
print('MSE :' , metrics.mean_squared_error(y_test,y_predict))
print('RMSE :' , np.sqrt(metrics.mean_squared_error(y_test,y_predict)))


MAE : 5.4496942971539895
MSE : 31.556542406092696
RMSE : 5.617521019639597


In [47]:
score=model.score(x_test,y_test)
print(score)
print(f"{score*100 :.2f}","%")

0.8944542088325094
89.45 %


In [49]:
#r2 score
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_predict)
print('R2 score : ',r2)
print(f"{r2*100 :.2f}","%")


R2 score :  0.8944542088325094
89.45 %



*Scaling*

In [54]:
#SCALING---Normalizing----standardizing
df = pd.DataFrame({
   'Income': [15000, 1800, 120000, 10000],
   'Age': [25, 18, 42, 51],
   'Department': ['HR','Legal','Marketing','Management']
})


In [55]:
dfc=df.copy()
features=dfc[['Income','Age']]

In [58]:
from sklearn.preprocessing import MinMaxScaler
#x_scaled = (x – x_min)/(x_max – x_min)
scaler = MinMaxScaler(feature_range=(5,10))
dfc[['Income','Age']] = scaler.fit_transform(features.values)
dfc


Income        Age  Department
0   5.558376   6.060606          HR
1   5.000000   5.000000       Legal
2  10.000000   8.636364   Marketing
3   5.346870  10.000000  Management

In [57]:
dfcc=df.copy()
features=dfcc[['Income','Age']]
#standard scaler
from sklearn.preprocessing import StandardScaler
#x_scaled = x – mean/std_dev
scaler=StandardScaler()
dfcc[['Income','Age']] = scaler.fit_transform(features.values)
dfcc


Income       Age  Department
0 -0.449056 -0.685248          HR
1 -0.722214 -1.218219       Legal
2  1.723796  0.609110   Marketing
3 -0.552525  1.294358  Management