#Logistic_Regression

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

In [3]:
from sklearn.datasets import load_breast_cancer
dt = load_breast_cancer()
# Read the DataFrame, first using the feature data
data = pd.DataFrame(dt.data, columns=dt.feature_names)
# Add a target column, and fill it with the target data
data['outcome'] = dt.target
# Show the first five rows
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  outcome  
0          0.4601                  0.11890        0  
1          0.2750                  0.08902        0  
2          0.3613                  0.08758        0  
3          0.6638                  0.17300        0  
4          0.2364                  0.07678        0  

[5 rows x 31 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [8]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension     outcome  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [4]:
data['mean radius'].mean()

14.127291739894552

In [9]:
x=data.iloc[:,:-1]
y=data.outcome

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [11]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=10000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [12]:
y_predict=model.predict(x_test)

In [13]:
y_predict

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [17]:
#cross tab
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))
pd.crosstab(y_test,y_predict)

0.9532163742690059


col_0     0    1
outcome         
0        57    2
1         6  106

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93        59
           1       0.98      0.95      0.96       112

    accuracy                           0.95       171
   macro avg       0.94      0.96      0.95       171
weighted avg       0.96      0.95      0.95       171



In [19]:
model.predict_proba(x_test)

array([[9.91931395e-01, 8.06860525e-03],
       [2.85541446e-06, 9.99997145e-01],
       [5.22250143e-04, 9.99477750e-01],
       [9.99958881e-01, 4.11192764e-05],
       [9.23587894e-04, 9.99076412e-01],
       [4.51586638e-04, 9.99548413e-01],
       [3.24626230e-05, 9.99967537e-01],
       [5.89288247e-01, 4.10711753e-01],
       [9.99998482e-01, 1.51787357e-06],
       [9.94492724e-01, 5.50727601e-03],
       [3.37058309e-05, 9.99966294e-01],
       [3.87637977e-05, 9.99961236e-01],
       [7.80464516e-01, 2.19535484e-01],
       [2.71659491e-04, 9.99728341e-01],
       [9.99814090e-01, 1.85909837e-04],
       [9.95317261e-01, 4.68273895e-03],
       [2.13842224e-04, 9.99786158e-01],
       [1.52984179e-01, 8.47015821e-01],
       [1.78031728e-02, 9.82196827e-01],
       [8.15805001e-01, 1.84194999e-01],
       [8.92997016e-01, 1.07002984e-01],
       [5.88905237e-01, 4.11094763e-01],
       [1.16513715e-03, 9.98834863e-01],
       [1.39748711e-02, 9.86025129e-01],
       [9.999999

In [30]:
y_predict_th3=np.where(model.predict_proba(x_test)[:,1]>0.3,1,0)


In [31]:
print(pd.crosstab(y_test,y_predict_th3))


col_0     0    1
outcome         
0        55    4
1         5  107


In [20]:
def predict_threshold(model,x_test,threshold):
    return np.where(model.predict_proba(x_test)[:,1]>threshold,1,0)

In [29]:
from sklearn.metrics import confusion_matrix
for thr in np.arange(0,1.0,0.1):
    y_predict=predict_threshold(model,x_test,thr)
    print('threshold :',thr)
    #print(pd.crosstab(y_test,y_predict))
    print(confusion_matrix(y_test,y_predict))
    print(accuracy_score(y_test,y_predict))



threshold : 0.0
col_0      1
outcome     
0         59
1        112
[[  0  59]
 [  0 112]]
0.6549707602339181
threshold : 0.1
col_0     0    1
outcome         
0        52    7
1         4  108
[[ 52   7]
 [  4 108]]
0.935672514619883
threshold : 0.2
col_0     0    1
outcome         
0        54    5
1         5  107
[[ 54   5]
 [  5 107]]
0.9415204678362573
threshold : 0.30000000000000004
col_0     0    1
outcome         
0        55    4
1         5  107
[[ 55   4]
 [  5 107]]
0.9473684210526315
threshold : 0.4
col_0     0    1
outcome         
0        56    3
1         5  107
[[ 56   3]
 [  5 107]]
0.9532163742690059
threshold : 0.5
col_0     0    1
outcome         
0        57    2
1         6  106
[[ 57   2]
 [  6 106]]
0.9532163742690059
threshold : 0.6000000000000001
col_0     0    1
outcome         
0        57    2
1         6  106
[[ 57   2]
 [  6 106]]
0.9532163742690059
threshold : 0.7000000000000001
col_0     0    1
outcome         
0        57    2
1         6  106
[[ 57